// MATCHES
export const FETCHING_MATCHES = 'FETCHING_MATCHES';
export const FETCHING_MATCHES_SUCCESS = 'FETCHING_MATCHES_SUCCESS';
export const FETCHING_MATCHES_ERROR = 'FETCHING_MATCHES_ERROR';

export const TOGGLE_NOTIFICATION = 'TOGGLE_NOTIFICATION';
