// MATCHES
export const FETCHING_MATCHES = 'FETCHING_MATCHES';
export const FETCHING_MATCHES_SUCCESS = 'FETCHING_MATCHES_SUCCESS';
export const FETCHING_MATCHES_ERROR = 'FETCHING_MATCHES_ERROR';

// USER
export const FETCHING_LOGIN = 'FETCHING_LOGIN';
export const FETCHING_LOGIN_SUCCESS = 'FETCHING_LOGIN_SUCCESS';
export const FETCHING_LOGIN_ERROR = 'FETCHING_LOGIN_ERROR';
export const FETCHING_LOGOUT = 'FETCHING_LOGOUT';
export const FETCHING_LOGOUT_SUCCESS = 'FETCHING_LOGOUT_SUCCESS';
export const FETCHING_LOGOUT_ERROR = 'FETCHING_LOGOUT_ERROR';

// CONFIG
export const FETCHING_CONFIG = 'FETCHING_CONFIG';
export const FETCHING_CONFIG_SUCCESS = 'FETCHING_CONFIG_SUCCESS';
export const FETCHING_CONFIG_ERROR = 'FETCHING_CONFIG_ERROR';
export const SET_CURRENT_WEEK = 'SET_CURRENT_WEEK';

export const TOGGLE_NOTIFICATION = 'TOGGLE_NOTIFICATION';
